### ISSUE TITLE
SME Review Checklist

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-cloud-aws#12]
SME Review<br/><br/>- [ ] Ensure technical accuracy for code<br/>- [ ] Ensure technical accuracy for guide<br/>- [ ] Ensure technical accuracy for overall content

**Comment by andrewdes** [comment]
SME gave the following feedback: 
- [ ] you specify t2.small worker nodes, which is just 1 core, 2GB memory.  is that a good recommendation for worker node size for running two java microservices?  presumably we’re deploying to EKS over minikube because it’s for “production” and is “highly available”
- [ ] similarly the kube yaml has no resource requests or limits in the deployment, which developers should really add since this affects whether workloads get evicted
- [ ] might be also helpful to have a healthcheck in the deployment yaml (and code), partifularly you do a rolling update but i think kube just kills the old container and sends traffic to the new one without seeing if the new container is ready yet
- [ ] it might be useful to review some of the AWS capabilities with EKS for collecting logs and metrics, particularly how openliberty can expose metrics and logs to external tools, particularly cloudwatch
- [ ] you specify NodePort service types and then you need to manually open the security groups.  would it be better to use LoadBalancer service type here?  it will result in an ELB created for each service and the security groups should be opened automatically.  In general if the idea is to allow developers to be able to develop microservices with minimal operations knowledge, having to call an operations guy to step in and open NodePorts on security groups should be discouraged.  understandably there may be cost concerns with allowing developers to just create LoadBalancers as well.

**Comment by andrewdes** [comment]
@gkwan-ibm

**Comment by yeekangc** [comment]
We should call out these considerations where appropriate in the guide e.g. size of the nodes.

I am open to adding Health Check, integrating it with Kube and having it there OOTB.  This is good practice though it won't be the focus of this guide here.

Yes, capabilities for logs and metrics should be a separate guide.

**Comment by jkwong888** [comment]
regarding resource requests, limits and health check, these should really be in the examples, even if you don't discuss them.  resource requests and limits tell the platform how to place containers and also become important for autoscaling.  health check shouldn't be optional as it's especially important during your rolling update as without one you'll be taking downtime when you roll the deployment over.

for logging, you may want to have the guide show how to stream the container logs using kubectl, even if you don't use cloudwatch.  the base container image with the app server probably configures logging to std out which is enough to plug into logging frameworks.

in general I don't think we should be recommending NodePort unless it's in development only scenarios like in minikube.  additionally, i think only a user facing service like an API or frontend you expose outside of the cluster would need a LoadBalancer service type; if it's an internal API like a backend microservice, you may be able to get away with running a pod from inside the cluster that calls curl.  LoadBalancer typically needs an external cloud provider integration (in AWS case, ELB is created); on other kube platforms it really depends on if the cloud provider integration is present.

there's nothing really in this guide specific to AWS beyond how to create an EKS cluster or use ECR, which might make it easy to re-use some of the materials that are kube agnostic (i.e. the yamls).

**Comment by jkwong888** [comment]
btw i don't know if this is a nit or not but we mention "docker" and "docker images" a lot, where I think we might want to just call them "containers" and "container images" ... docker is a particular developer toolset to build container images, which technically is not necessary to run a container is kubernetes.  it's fine that we use "Docker" and "Dockerfile" to create the image, but once it's built it's a "container image" and when it's running it's a "containers"

**Comment by evelinec** [comment]
Team have determined to work on the rest of the issue post publishing.
