### ISSUE TITLE
Peer Review/Testing Checklist

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-cloud-aws#14]
Peer Review 

- [x] Working instruction and sample code
- [x] Quality of code (best coding practices)
- [x] Quality and presentation of guide according to Structure and Style Guideline
- [x] Consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the pom.xml, server.xml, etc files are clean up
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Liniux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try curl command where applicable 
- [x] Ensure that the guide is using the latest version of the liberty-maven-plugin or gradle plugin
- [x] Check that some of these page-tags are used in a guide: MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security. Only these tags are visible on the website. Latest list here. 
- [x] Check that other tags relevant to the guide are added. These will not be visible on the website, but can help the guide to be searchable. 
- [x] Check the attribution statement is accurate for the guide. 

Peer Testing

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Define test coverage and review with team (including guide contributor, if available)
- [ ] Define detail test cases
- [ ] Consider corner cases targeting the specific guide
- [ ] Consider different platform tests, ie, Mac, Windows, Linux – New!
- [ ] Consider corner cases UI tests
- [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari - New!
- [ ] Consider testing the curl command for URL visits
- [x] Consider Consider building with both Maven and Gradel build tools
- [ ] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, (Microclimate) - New!
- [x] Run Acrolink Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides
- [x] Ensure automated test is enable, setup with Travis CI, and schedule tests
- [x] Run diff -r start/ finish/
- [x] Ensure that the automation tests are able to run with continuous daily build

Peer Tester’s responsibility:
- [x] Check the appearance of the guide on test site for the following items:
- Table of contents
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by justineechen** [comment]
**Why use Kubernetes services in the cloud?**


**Prerequisites**
- [ ] Add `latest` Python version 
- [ ] Add details for creating the user account 
  - Clicking Users to start 
  - AWS access type should be specified, I chose programmatic access. 
- [ ] After running aws configure,  does the user need to fill out Default region name/Default output format?  If so, what is Default output format/what are they expecting? 
  - If the default region name is filled out with something other than the correct list of region names (or maybe none) you can't execute eksctl later, so the specific parameters to enter (or not enter) really needs to be clearer in this step. 

**Deploying microservices to Amazon Elastic Container Service for Kubernetes (EKS)**
- [ ] Remove the white space before `Provisioning a cluster`
- [ ] Capitalize `Installing aws-iam-authenticator` (just the I in installing)
- [ ] `Navigate to the eksctl release page and download the latest stable release. Extract the archive and add the directory with the extracted files to your path.` did not work for me for some reason but I followed other instructions here: https://linoxide.com/linux-how-to/eksctl-create-kubernetes-cluster-amazon-eks/
- [ ] Include kubernetes prerequisites/instructions before asking users to use `kubectl`

**Comment by justineechen** [comment]
- Tested on Windows, everything looks good there

**Comment by justineechen** [comment]
Testing on linux
- after running eksctl create cluster... 
```
[ℹ]  using region us-east-1
[ℹ]  setting availability zones to [us-east-1d us-east-1c]
[ℹ]  subnets for us-east-1d - public:192.168.0.0/19 private:192.168.64.0/19
[ℹ]  subnets for us-east-1c - public:192.168.32.0/19 private:192.168.96.0/19
[ℹ]  nodegroup "ng-b560b166" will use "ami-0535079027b14e972" [AmazonLinux2/1.11]
[ℹ]  creating EKS cluster "guide-cluster" in "us-east-1" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-1 --name=guide-cluster'
[ℹ]  building cluster stack "eksctl-guide-cluster-cluster"
[ℹ]  creating nodegroup stack "eksctl-guide-cluster-nodegroup-ng-b560b166"
[ℹ]  --nodes-min=1 was set automatically for nodegroup ng-b560b166
[ℹ]  --nodes-max=1 was set automatically for nodegroup ng-b560b166
[✔]  all EKS cluster resource for "guide-cluster" had been created
[✔]  saved kubeconfig as "/home/ibmadmin/.kube/config"
[ℹ]  adding role "arn:aws:iam::208872073932:role/eksctl-guide-cluster-nodegroup-ng-NodeInstanceRole-MFZ3TNWD9OG9" to auth ConfigMap
[ℹ]  nodegroup "ng-b560b166" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "ng-b560b166"
[ℹ]  nodegroup "ng-b560b166" has 1 node(s)
[ℹ]  node "ip-192-168-29-240.ec2.internal" is ready
[✖]  kubectl not found, v1.10.0 or newever is required
[ℹ]  cluster should be functional despite missing (or misconfigured) client binaries
[✔]  EKS cluster "guide-cluster" in "us-east-1" region is ready
```

**Comment by justineechen** [comment]
- Needs clear instructions on installing `Docker` and installing `kubectl`, similar to installing `awscli`. and `eksctl`

**Comment by justineechen** [comment]
- Testing on Linux
  - after running `aws ecr get-login --no-include-email`, I got `Unknown options: --no-include-email` 
  - my aws version is `aws-cli/1.11.13` which doesn't match what it says on the install page so I'll try to uninstall and see although I followed the install instructions from the page

**Comment by justineechen** [comment]
- Year licenses for many java files only say 2018 (need to add 2019) 
- Year license for index.html says 2016 (need to add 2019)

**Comment by andrewdes** [comment]
@justineechen changes were made here: https://github.com/OpenLiberty/draft-guide-cloud-aws/commit/fb0164c6ffee8b87817fb7415bce4b4e8d80a67c and https://github.com/OpenLiberty/draft-guide-cloud-aws/commit/7c57ddeb3e083c0fbbd1b8dec32c4f26ff8a8d12.

See the below notes about certain points:

>  `Navigate to the eksctl release page and download the latest stable release. Extract the archive and add the directory with the extracted files to your path`.did not work for me for some reason but I followed other instructions here: https://linoxide.com/linux-how-to/eksctl-create-kubernetes-cluster-amazon-eks/

Turns out you were downloading the wrong file. After downloading the correct one, this worked for you right?

> curl http://[ip-address].. failed to connect both times for me

>  mvn verify fails

After a discussion with you, you were substituting in the incorrect IP address. After substituting in the `External_ip` these worked successfully for you correct? I also added some instructions to make it more clear which IP to use.

> after running aws ecr get-login --no-include-email, I got Unknown options: --no-include-email

You must not have had the latest AWS CLI version (which is why it worked after upgrading). Made a note of this in the guide.

> It should be made more clear to save the URI somehow.. not sure how to do that yet but this really slows down the flow of the guide here.

Not really sure how to do this, since it will be a different URI for every user/repository. Any suggestions?

**Comment by justineechen** [comment]
- [ ] Prerequisites section.. maybe some subsections or bullet points would help to make it clear like this is - kubectl - aws cli just to make it clear there are two things they need to set up because `Before you begin, have the following tools installed:` seems ambiguous to me

- I wonder if it would be worthwhile to also put `eksctl` and `aws-iam-authenticator` in this section as well to keep everything uniform. Do those things need to be put closest to the command necessarily or would it be easier to get the user to download everything at once? 

- [ ] Use either EXTERNAL-IP or ip-address throughout the guide to describe that same IP instead of having two different titles for it

**Comment by andrewdes** [comment]
@justineechen I made changes and opened a PR here: https://github.com/OpenLiberty/draft-guide-cloud-aws/pull/15

> I wonder if it would be worthwhile to also put eksctl and aws-iam-authenticator in this section as well to keep everything uniform. Do those things need to be put closest to the command necessarily or would it be easier to get the user to download everything at once?

I personally like them in the `Provisioning a cluster` section since they are exclusive to provisioning the cluster. The other pre-reqs are items that get used consistently throughout the guide/general tools used during the guide. So I personally like the explanation/introduction of the `aws-iam-authenticator` and `eksctl` in the section. What are your thoughts on this?

> Use either EXTERNAL-IP or ip-address throughout the guide to describe that same IP instead of having two different titles for it

The `EXTERNAL-IP` is the public ip address of the node (AWS labels this the `EXTERNAL-IP`, on IKS I believe it is `PUBLIC-IP`, etc.). Whereas `ip-address` is just a placeholder that can be replaced with any ip-address. In the case of this guide we are using `NodePort` so it happens to be the `EXTERNAL-IP`, however, if someone following the guide decides to use a `LoadBalancer` (or expose their deployments in a different way), this `ip-address` placeholder might not be replaced by the `EXTERNAL-IP` of the node.

**Comment by justineechen** [comment]
@andrewdes 
- I understand that.. then I wonder if it would be nicer to have the prerequisites right before this section. I think it would be nice to keep all the downloads together. But it's not completely necessary, maybe you can give it more thought if someone gives the same feedback,

- Is there a section where you explicitly say `EXTERNAL-IP` is the `[ip-address]` in the guide? Maybe that could be made more clear

**Comment by andrewdes** [comment]
@justineechen 

- I gave this some more thought and I am ok moving these two to the pre-req section and then just explaining them in more detail in the `Provisioning a cluster` section.

- Yes, after instructing the user to take note of the `EXTERNAL-IP` I mention that this is the ip-address they will need to substitute in later on in the guide.

**Comment by andrewdes** [comment]
@justineechen All your feedback has been addressed, can this issue be closed?

**Comment by evelinec** [comment]
@justineechen how was the following point being done: 

- Ensure that the automation tests are able to run with continuous daily build
